# Generated by Django 4.1 on 2023-02-11 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=225)),
                ('organization', models.CharField(default='Kartexa', max_length=255)),
                ('organizer', models.CharField(max_length=225)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
