# Generated by Django 4.1 on 2023-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_link',
            field=models.URLField(default='demo'),
        ),
    ]
