# Generated by Django 4.1 on 2023-02-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate_qr_image_certificate_verification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='internship_name',
            field=models.CharField(default='demo', max_length=225),
        ),
    ]
